# Server Port (Cloud assigns a port, local uses 8080)
server.port=${PORT:8080}

# Database Connection (Cloud uses DB_URL, local uses localhost)
spring.datasource.url=${DB_URL:******Use your own db instance}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:***** Use your own password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf Configuration (Disable cache for dev)
spring.thymeleaf.cache=false
