# Server Port
server.port=8080

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/agri_shop_db
spring.datasource.username=postgres
# REPLACE 'your_password' WITH YOUR ACTUAL POSTGRES PASSWORD
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
# 'update' keeps data but updates schema.
# WARNING: Use 'validate' in production later.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf Configuration (Disable cache for dev)
spring.thymeleaf.cache=false